### ISSUE TITLE
Can't access cluster headnode whose version is 3.7.0 

### ISSUE THREAD

**Issue by rapirent** [aws/aws-parallelcluster-ui#258]
## Description
I have created a cluster headnode with parallelcluster-cli, and assumed that it would work with parallelcluster-ui. 
And I see there is no new release for parallelcluster UI.

## Steps to reproduce the issue
1. Creating a headnode in the region with newest parallelcluster cli.
2. Clicking the headnode just created in parallelcluster ui in same region.

## Expected behaviour
It should work.

## Actual behaviour
<img width="1870" alt="image" src="https://github.com/aws/aws-parallelcluster-ui/assets/15178515/84d2a95d-6fa2-4b39-b0cf-d48a04c59b90">

## Required info
In order to help us determine the root cause of the issue, please provide the following information:
- Region where ParallelCluster UI is installed: us-east-2
- Version of ParallelCluster UI and ParallelCluster: ParallelCluster UI 3.6.0, ParallelCluster 3.7.0

## Additional info
The following information is not required but helpful:
 - OS: macOS
 - Browser: Chrome

**Comment by mendaomn** [comment]
Thank you for the detailed description of the issue

ParallelCluster does not support clusters created with major/minor versions greater than the current ParallelCluster version. 

In other words, the error you are seeing is linked to the fact that PCUI is shipping PC 3.6.0, while the cluster was created with PC 3.7.0

Unfortunately I cannot share an ETA for an official release supporting PC 3.7.0. It is however possible to specify a different PC version when installing PCUI. Please keep in mind it is not officialy supported yet.

In order to that you would use the official links https://docs.aws.amazon.com/parallelcluster/latest/ug/install-pcui-v3.html and specify in the CloudFormation parameters the PC version you want to ship with PCUI.

**Comment by gmarciani** [comment]
This issue will be solved by the next upcoming release 2023.10.0

**Comment by gmarciani** [comment]
Released: https://github.com/aws/aws-parallelcluster-ui/releases/tag/2023.10.0
