### ISSUE TITLE
Can't edit cluster "Something went wrong"

### ISSUE THREAD

**Issue by cartalla** [aws/aws-parallelcluster-ui#69]
When trying to edit a cluster I get "Something went wrong".

I get this error whether the compute fleet is running or not.

Instructions to reproduce:

1. Select cluster
2. Select Edit
3. Cluster: Select Next
4. Head node: Select Next

Hit the error dialog box.

I tried logging out and back in and still get the error.

Version: 3.5.0
Browser: Firefox
[edapc3-config.txt](https://github.com/aws/aws-parallelcluster-ui/files/10825829/edapc3-config.txt)

**Comment by mtfranchetto** [comment]
Hi @cartalla, can you attach the YAML config of the selected cluster? Also, it would help to see the logs from PCUI.

**Comment by mtfranchetto** [comment]
Which version of ParallelCluster are you using? And which browser? Every additional data can help.

**Comment by cartalla** [comment]
> Hi @cartalla, can you attach the YAML config of the selected cluster? Also, it would help to see the logs from PCUI.

Where are the PCIU logs? I'm looking in CW and the APIGatewayAccessLog only has ip addresses.
I'm looking in the Lambda log, but not seeing an error there.

**Comment by mtfranchetto** [comment]
I sent you a link on Slack: I'm sorry but we still haven't published the Logs guide.

**Comment by cartalla** [comment]
[logs-insights-results.json.txt](https://github.com/aws/aws-parallelcluster-ui/files/10826207/logs-insights-results.json.txt)

**Comment by mtfranchetto** [comment]
This bug has been fixed with https://github.com/aws/aws-parallelcluster-ui/pull/53, but unfortunately, it's still not released.
We'll try to release this bugfix as soon as possible, and in the meantime you can try to update the internal Lambda function of PCUI by running the [build_and_update_lambda.sh](https://github.com/aws/aws-parallelcluster-ui/blob/main/scripts/build_and_update_lambda.sh) script manually on your PCUI stack.

**Comment by cartalla** [comment]
I was able to install docker and run the script and it resolved the problem which was triggered by having multiple storage volumes configured.
